  const predefinedCities = [
    { city: "New York", country: "US" },
    { city: "Los Angeles", country: "US" },
    { city: "Chicago", country: "US" },
    { city: "London", country: "GB" },
    { city: "Paris", country: "FR" },
    { city: "Berlin", country: "DE" },
    { city: "Madrid", country: "ES" },
    { city: "Rome", country: "IT" },
    { city: "Amsterdam", country: "NL" },
    { city: "Moscow", country: "RU" },
    { city: "Beijing", country: "CN" },
    { city: "Shanghai", country: "CN" },
    { city: "Tokyo", country: "JP" },
    { city: "Seoul", country: "KR" },
    { city: "Bangkok", country: "TH" },
    { city: "Jakarta", country: "ID" },
    { city: "Mumbai", country: "IN" },
    { city: "New Delhi", country: "IN" },
    { city: "Dubai", country: "AE" },
    { city: "Riyadh", country: "SA" },
    { city: "Istanbul", country: "TR" },
    { city: "Cairo", country: "EG" },
    { city: "Johannesburg", country: "ZA" },
    { city: "Sydney", country: "AU" },
    { city: "Melbourne", country: "AU" },
    { city: "São Paulo", country: "BR" },
    { city: "Buenos Aires", country: "AR" },
    { city: "Mexico City", country: "MX" },
    { city: "Toronto", country: "CA" },
    { city: "Vancouver", country: "CA" },
];

export default predefinedCities;